#!/usr/bin/env python
import sys
foundKey = ""
foundValue = ""
isFirst = 1
currentCount = 0
# remember - we want it to sort last
currentcountyname = "Z"
currentstate2digit = "Z"
isCountryMappingLine = False
# STDIN - watch indents and note unix pipe
for line in sys.stdin:
    # remove leading and trailing whitespace.
    line = line.strip()

    try:
        # parse the input we got from mapper.py
        FiveDigitCode,countyname,State2digit,Population = line.split('^')
	  # the first line should be a mapping line from sort.
        if State2digit == "Z":
            currentCountyname = countyname
            currentCountry2digit = state2digit
            isCountryMappingLine = True
        else:
                # this is a new county.
            isCountryMappingLine = False

        # we want to count counties by state. 
        if not isCountryMappingLine:

            # we only need a single key of state code. 
            currentKey = '%s' % (State2digit)
		# change keys for new state
            if foundKey != currentKey:
                if isFirst == 0:
                    print '%s\t%s' % (foundKey,currentCount)
                    currentCount = 0 #reset the count
                else:
                    isFirst = 0

                # make new state key.
                foundKey = currentKey

             
            currentCount += 1
    except: pass
print '%s\t%s' % (foundKey,currentCount)

